export const KEYWORDS: string[] = [
  // English — tech & SEO
  "nodejs best practices",
  "react vs vue 2024",
  "docker container tutorial",
  "python machine learning",
  "javascript async await",
  "typescript generics",
  "postgresql vs mysql",
  "redis caching strategies",
  "kubernetes deployment guide",
  "web scraping with python",
  "seo keyword research tools",
  "google ranking factors",
  "backlink building strategies",
  "on page seo checklist",
  "site speed optimization",
  "core web vitals guide",
  "technical seo audit",
  "content marketing tips",
  "local seo for small business",
  "ecommerce seo strategy",
  "nextjs tutorial beginner",
  "graphql vs rest api",
  "microservices architecture",
  "devops ci cd pipeline",
  "aws lambda functions",
  "cloudflare workers tutorial",
  "linux server setup guide",
  "nginx reverse proxy",
  "mongodb aggregation",
  "elasticsearch full text search",
  "tailwindcss components",
  "shadcn ui setup",
  "prisma orm tutorial",
  "supabase vs firebase",
  "vercel deployment guide",
  "github actions workflow",
  "websocket real time app",
  "jwt authentication nodejs",
  "oauth2 implementation",
  "api rate limiting strategies",

  // Vietnamese
  "lập trình web cho người mới bắt đầu",
  "học javascript cơ bản",
  "thiết kế website bán hàng",
  "tối ưu hóa công cụ tìm kiếm",
  "từ khóa seo tiếng việt",
  "cách tăng traffic website",
  "marketing online hiệu quả",
  "kinh doanh online 2024",
  "học tiếng anh online",
  "du lịch việt nam",
  "món ăn ngon hà nội",
  "công thức nấu ăn đơn giản",
  "chăm sóc sức khỏe tại nhà",
  "đầu tư chứng khoán cho người mới",
  "học lập trình python",
  "framework nodejs express",
  "database mysql cơ bản",
  "api restful là gì",
  "docker là gì và cách dùng",
  "github cách sử dụng",
  "reactjs tutorial tiếng việt",
  "xây dựng app mobile",
  "flutter vs react native",
  "startup công nghệ việt nam",
  "freelancer lập trình",
  "làm giàu online",
  "crypto bitcoin 2024",
  "bất động sản hà nội",
  "việc làm lập trình viên",
  "kỹ năng mềm cần thiết",

  // Japanese
  "プログラミング 初心者 学習",
  "JavaScript フレームワーク 比較",
  "React チュートリアル 2024",
  "SEO 対策 方法",
  "ウェブデザイン トレンド",
  "Pythonで機械学習",
  "データベース 設計 基礎",
  "クラウドサービス 比較",
  "フリーランス エンジニア",
  "転職 エンジニア 方法",
  "東京 観光 スポット",
  "日本料理 レシピ",
  "健康管理 アプリ",
  "株式投資 初心者",
  "英語学習 アプリ",
  "リモートワーク 仕事",
  "副業 おすすめ",
  "スタートアップ 日本",
  "AIツール 活用方法",
  "ノーコード ツール",
  "TypeScript 入門",
  "Docker 使い方",
  "API 設計 ベストプラクティス",
  "GitHubの使い方",
  "Linux コマンド 基礎",
  "ネットワーク セキュリティ",
  "クリプト 投資 2024",
  "ゲーム開発 Unity",
  "動画編集 ソフト",
  "ブログ 収益化 方法",
];
